#- name: Server Check up
#  hosts: ansible_network_health_check_to
#  gather_facts: yes
#  tasks:
  - name: Check server status
#    when: check_to_host ==  inventory_hostname
    delegate_to: "{{check_to_host}}"
    with_lines:
      - "/tmp/ansible_network_health_check_to/{{test_protocol}}_{{test_to_ip}}_{{test_port}}_OUTPUT"
    include_tasks: tasks/register_test_result.yaml
    vars:
      test_result_string: "{{item}}"

  - name: Ensure no existing process running
    delegate_to: "{{check_to_host}}"
#    when: check_to_host ==  inventory_hostname
    shell: |
      for PIDFILE in $(ls /tmp/ansible_network_health_check_to/*PID); do
         kill -9 $(cat $PIDFILE)
      done
      exit 0

  - name: ensure tmp folder doesnot exist for clean start
    delegate_to: "{{check_to_host}}"
#    when: check_to_host ==  inventory_hostname
    file:
      path: /tmp/ansible_network_health_check_to/
      state: absent
